### ISSUE TITLE
Errors after running on Win10

### ISSUE THREAD

**Issue by jessefmoore** [zeronetworks/BloodHound-Tools#6]
Thanks for your help on this!
Using PowerShell Administrator Prompt.. Python3.10 downloaded from MSFT Store and I get these errors AFTER clearing the Database in BloodHound 4:
New Settings:
DB Url: bolt://localhost:7687
DB Username: neo4j
DB Password: BloodHound
Use encryption: False

Testing DB Connection
Database Connection Successful!
(Cmd) connect
Database Connection Successful!
(Cmd) generate
Starting data generation with nodes=500
Populating Standard Nodes
Traceback (most recent call last):
  File ".\DBCreator_randNetAccess.py", line 902, in <module>
    MainMenu().cmdloop()
  File ".\DBCreator_randNetAccess.py", line 70, in cmdloop
    cmd.Cmd.cmdloop(self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File ".\DBCreator_randNetAccess.py", line 216, in do_generate
    self.generate_data()
  File ".\DBCreator_randNetAccess.py", line 304, in generate_data
    "DEFAULT DOMAIN CONTROLLERS POLICY"), guid=ddp)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\neo4j\work\simple.py", line 218, in run
    self._bookmarks, **kwparameters
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\neo4j\work\result.py", line 114, in _run
    self._attach()
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\neo4j\work\result.py", line 203, in _attach
    self._connection.fetch_message()
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\neo4j\io\_common.py", line 167, in inner
    func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\neo4j\io\_bolt4.py", line 309, in fetch_message
    response.on_failure(summary_metadata or {})
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\neo4j\io\_common.py", line 225, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.ConstraintError: {code: Neo.ClientError.Schema.ConstraintValidationFailed} {message: Node(9) already exists with label `Base` and property `objectid` = 'adfce851-e0bb-4129-af67-4033983fa60a'}
PS C:\Users\Administrator\Downloads\BloodHound-Tools-main\BloodHound-Tools-main\DBCreator>

**Comment by sagiesec** [comment]
I'm not sure how to recreate this issue, but it does look like an error during one of the queries. 
When clearing the data, I find it easiest with the following command: "MATCH (n) DETACH DELETE n". 
If this doesn't work, try reinstalling the neo4j and rerun. 
Please let me know if the issue persists.
